apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mediawiki-ingress                     # Name des Ingress-Objekts
  namespace: m347-mediawiki                   # Namespace, in dem der dieser Ingress gespeichert ist
spec:
  ingressClassName: nginx
  rules:
    - host: mediawiki.m347.ch                 # Hostname (f√ºr den lokalen Zugriff)
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: mediawiki-service       # Name des Ziel-Services
                port:
                  number: 80
            
